DjangoEcommerceWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
from .api_urls import router

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('api-token-auth/', obtain_auth_token),
                  path('api/', include(router.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import detail, add_cart, remove_cart

app_name = 'cart'
urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('remove/<int:product_id>/', remove_cart, name='remove_cart'),
]

orders/urls.py
from django.urls import path
from .views import create_order, order_detail, send_request, verify

app_name = 'orders'
urlpatterns = [
    path('create/', create_order, name='create'),
    path('detail/<int:order_id>/', order_detail, name='detail'),
    path('request/', send_request, name='request'),
    path('verify/', verify, name='verify'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from shop.models import Product


class AddCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10, label='',
                                  widget=forms.NumberInput(attrs={'placeholder': 'تعداد', 'class': 'form-control'}))

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AddCartForm
from shop.models import Product
from .cart_session import Cart
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required


@login_required
def detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@login_required
def add_cart(request, product_id):
    if request.method == 'POST':
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = AddCartForm(request.POST)
        if form.is_valid():
            cart.add(product=product, quantity=form.cleaned_data['quantity'])
    return redirect('cart:detail')


def remove_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container col-md-7 mt-5">
        <table class="table table-sm table-hover">
            <thead class="table-light">
            <tr>
                <th scope="col">ردیف</th>
                <th scope="col">نام محصول</th>
                <th scope="col">تعداد</th>
                <th scope="col">قیمت واحد(ریال)</th>
                <th scope="col">قیمت کل(ریال)</th>
                <th scope="col">حذف</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_item_price }}</td>
                <td><a href="{% url 'cart:remove_cart' item.product.id %}"><i class="bi bi-trash text-danger"></i></a>
                </td>
            {% endfor %}
            </tbody>
            <th>
            <td colspan="3">جمع کل فاکتور</td>
            <td>{{ cart.get_total_price }} ریال</td>
            <td>
                <a href="{% url 'orders:create' %}" class="btn btn-sm btn-success text-decoration-none">
                    <i class="bi bi-cart-check-fill"> ثبت سفارش و پرداخت
                    </i>
                </a>
            </td>
            </th>
        </table>
    </div>
{% endblock content %}