DjangoEcommerceWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
from .api_urls import router

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('api-token-auth/', obtain_auth_token),
                  path('api/', include(router.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import detail, add_cart, remove_cart

app_name = 'cart'
urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('remove/<int:product_id>/', remove_cart, name='remove_cart'),
]

shop/urls.py
from django.urls import path, re_path
from .views import home, product_detail

app_name = 'shop'
urlpatterns = [
    re_path(r'd/(?P<code>\w+)/(?P<year>\w+)/(?P<month>\w+)/(?P<day>\w+)/(?P<slug>[-\w]+)/', product_detail,
            name='product_detail'),
    re_path(r'd/(?P<slug>[-\w]+)/', home, name='category_filter'),
    path('', home, name='home'),

]

shop/models.py
from django.db import models
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
from random import randint
from django.urls import reverse


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_categories',
                                     verbose_name='زیر مجمموعه', null=True, blank=True)
    is_sub = models.BooleanField(default=False, verbose_name='زیر مجموعه است')
    name = models.CharField(max_length=100, verbose_name='نام')
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True, verbose_name='شناسه')

    class Meta:
        ordering = ('name',)
        verbose_name = 'گروه'
        verbose_name_plural = '۱.گروه ها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_filter', args=[self.slug])


def random_int():
    return randint(10000000, 99999999)


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products', verbose_name='گروه')
    name = models.CharField(max_length=100, verbose_name='نام محصول')
    slug = models.SlugField(verbose_name='شناسه', max_length=100, unique=True, allow_unicode=True)
    description = models.TextField(verbose_name='توضیحات')
    price = models.PositiveIntegerField(verbose_name='قیمت')
    inventory = models.SmallIntegerField(verbose_name='موجودی')
    created = models.DateTimeField(auto_now_add=True, verbose_name='ایجاد محصول')
    updated = models.DateTimeField(auto_now=True, verbose_name='بروز رسانی محصول')
    code = models.IntegerField(default=random_int, editable=False, verbose_name='کد محصول')

    class Meta:
        ordering = ('name',)
        verbose_name = 'محصول'
        verbose_name_plural = '۲.محصولات'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.code, self.created.year, self.created.month, self.created.day, self.slug])


class ImageAlbum(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name='album', verbose_name='محصول')

    def default(self):
        return self.images.filter(default=True).first()

    def thumbnails(self):
        return self.images.filter(width__lt=100, length_lt=100)

    def __str__(self):
        return f"{self.product.name} - {self.product.category}"

    class Meta:
        verbose_name = 'آلبوم'
        verbose_name_plural = '۴.آلبوم ها'


class Picture(models.Model):
    image = models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='فایل عکس')
    default = models.BooleanField(default=False, verbose_name='پیش فرض')
    album = models.ForeignKey(ImageAlbum, on_delete=models.CASCADE, related_name='images', verbose_name='آلبوم عکس')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 800 or img.width > 800:
            output_size = (img.width / 2, img.height / 2)
            img.thumbnail(output_size)
            img.save(self.image.path)

    class Meta:
        verbose_name = 'عکس'
        verbose_name_plural = '۳.عکس ها'

    def __str__(self):
        return f"{self.id} - {self.album.product.name} - {self.album.product.category}"


@receiver(post_save, sender=Product)
def save_image_album(sender, instance, created, **kwargs):
    if created:
        related_album = ImageAlbum(product=instance)
        related_album.save()

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, ImageAlbum
from cart.forms import AddCartForm


def home(request, slug=None):
    products = Product.objects.filter(inventory__gt=0)
    categories = Category.objects.filter(is_sub=False)
    if slug:
        categories = Category.objects.filter(slug=slug)
    return render(request, 'shop/home.html', {'all_products': products, 'categories': categories})


def product_detail(request, code, year, month, day, slug):
    product = get_object_or_404(Product, slug=slug)
    categories = product.category.all()
    main_category = categories.filter(is_sub=False)
    sub_categories = categories.filter(is_sub=True)
    form = AddCartForm()
    return render(request, 'shop/product_detail.html',
                  {'product': product, 'main_category': main_category, 'sub_categories': sub_categories, 'form': form})

shop/templates/shop/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="bg-secondary p-3">
        {#  ***********************************  the carousel ****************************************** #}
        <div class="container card col-md-8 p-2 ">
            <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                            class="active"
                            aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
                            aria-label="Slide 4"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4"
                            aria-label="Slide 5"></button>

                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active" style="height: 18rem;">
                        <a href="{{ all_products.last.get_absolute_url }}">
                            <img src="{{ all_products.last.album.images.last.image.url }}" class="d-block w-100"
                                 alt="{{ all_products.last.album.images.last.album }}">
                        </a>
                        <div class="carousel-caption d-none d-md-block ">
                            <h4 class="d-flex justify-content-end font-weight-bold text-white mx-4 px-5">
                                {{ all_products.last }}
                            </h4>
                        </div>
                    </div>
                    {% with all_products|slice:4 as fourproducts %}
                        {% for product in fourproducts %}
                            <div class="carousel-item" style="height: 18rem;">
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.album.images.last.image.url }}" class="d-block w-100"
                                         alt="{{ product.album.images.last.album }}">
                                </a>
                                <div class="carousel-caption d-none d-md-block ">
                                    <h4 class="d-flex justify-content-end font-weight-bold text-white mx-4 px-5">
                                        {{ product.name }}
                                    </h4>
                                </div>
                            </div>
                        {% endfor %}
                    {% endwith %}
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
        {#  ***********************************  the products ****************************************** #}
        <div class="container card col-md-12 my-3 p-0">
            <div class="p-2" style="background-color: #ef394e">
                {% for category in categories %}
                    <a class="text-decoration-none text-dark" href="{{ category.get_absolute_url }}"><h4
                            class="p-2 bg-light rounded">{{ category.name }}</h4></a>
                    {% for product in category.products.all %}
                        <a href="{{ product.get_absolute_url }}">
                            <div class="card text-white m-2" style="width: 22rem;display: inline-block;">
                                {% for pic in product.album.images.all %}
                                    {% if pic.default %}
                                        <img class="card-img" src="{{ pic.image.url }}" alt="{{ pic.album }}">
                                    {% endif %}
                                {% endfor %}
                                <div class="card-img-overlay d-flex flex-column justify-content-end">
                                    <h4 class="card-title font-weight-bold">{{ product.name }}</h4>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="bg-light">
        <div class="jumbotron bg-light p-3">
            {#  ***********************************  the carousel ****************************************** #}
            <div class="container card col-md-8 p-2 ">
                <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                                class="active"
                                aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                                aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                                aria-label="Slide 3"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
                                aria-label="Slide 4"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4"
                                aria-label="Slide 5"></button>

                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active" style="height: 18rem;">
                            <img src="{{ product.album.images.last.image.url }}" class="d-block w-100"
                                 alt="{{ product }}">
                        </div>
                        {% with product.album.images.all|slice:4 as fourimages %}
                            {% for pic in fourimages %}
                                <div class="carousel-item" style="height: 18rem;">
                                    <img src="{{ pic.image.url }}" class="d-block w-100"
                                         alt="{{ product }}">
                                </div>
                            {% endfor %}
                        {% endwith %}
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                                data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                                data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
            {#  ***********************************  the product ****************************************** #}
            <div class="container card col-md-12 my-3 p-0" style="background-color: ghostwhite; ">
                <div class="p-4">
                    <div class="d-flex justify-content-between bg-white">
                        <small class="p-2 text-muted d-inline">
                            <a class="p-2 text-muted text-decoration-none"
                               href="{{ main_category.first.get_absolute_url }}">{{ main_category.first }}</a>
                            |
                            <a class="p-2 text-muted text-decoration-none"
                               href="{{ sub_categories.first.get_absolute_url }}">{{ sub_categories.first }}</a>
                        </small>
                        <small class="text-muted mx-5 my-2">
                            {% if product.inventory %}
                                <small class="text-success">🟢 موجود -</small>
                            {% else %}
                                <small class="text-danger">🔴 ناموجود -</small>
                            {% endif %}
                            {{ product.created|date }}
                        </small>
                    </div>

                    <div class="mx-2 my-3"><small>⚫</small>
                        <h4 class="text-muted mx-2 d-inline">{{ product }}</h4>
                    </div>
                    </a>
                    <hr>
                    <div class="row p-2">
                        <div class="col-md-4" style="text-align: justify;">
                            <small class="text-muted p-2">{{ product.description }}</small>
                            <hr>
                            <small class="text-muted">قیمت: {{ product.price }} ریال</small>
                            <small>
                                <form action="{% url 'cart:add_cart' product.id %}" method="post"
                                      class="form-group"> {% csrf_token %}
                                    <div class="container d-flex">
                                        {{ form }}
                                        <button type="submit" class="btn btn-success mx-2">
                                            <i class="bi bi-cart-plus-fill"></i>
                                        </button>
                                    </div>
                                </form>
                            </small>
                        </div>
                        <div class="col-md-8">
                            <img class="" src="{{ product.album.images.first.image.url }}" alt="{{ product }}"
                                 style="height: 30rem;">
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-light text-center">
                {% for pic in product.album.images.all %}
                    {% if forloop.counter >= 2 %}
                        <div class=" card-text-white m-2" style="width: 19rem;display: inline-block;">
                            <img class="card-img" src="{{ pic.image.url }}" alt="{{ pic.album }}">
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock content %}