DjangoEcommerceWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
from .api_urls import router

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('api-token-auth/', obtain_auth_token),
                  path('api/', include(router.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import user_login, user_logout, user_register

app_name = 'accounts'
urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
]

cart/urls.py
from django.urls import path
from .views import detail, add_cart, remove_cart

app_name = 'cart'
urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('remove/<int:product_id>/', remove_cart, name='remove_cart'),
]

shop/urls.py
from django.urls import path, re_path
from .views import home, product_detail

app_name = 'shop'
urlpatterns = [
    re_path(r'd/(?P<code>\w+)/(?P<year>\w+)/(?P<month>\w+)/(?P<day>\w+)/(?P<slug>[-\w]+)/', product_detail,
            name='product_detail'),
    re_path(r'd/(?P<slug>[-\w]+)/', home, name='category_filter'),
    path('', home, name='home'),

]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>

    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="position: relative">
    <div class="container-fluid col-md-10">
        <div class="d-flex justify-content-between col-md-9 ">
            <div class="d-flex">
                <a class="nav-link text-white" aria-current="page" href="{% url 'shop:home' %}">خانه</a>


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown" style="position: static;">
                            <a class="nav-link active dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink"
                               role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                محصولات
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink"
                                style="width: 50%;margin-right: 10%"
                            ">
                            {% for category in nav_categories %}
                                {% if not category.is_sub %}
                                    <ul class="list-inline text-light" style="display: inline-grid;margin-right: 10%">
                                        <a class="dropdown-item"
                                           href="{{ category.get_absolute_url }}">{{ category }}</a>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        {% for sub_category in category.sub_categories.all %}
                                            <li>
                                                <a class="dropdown-item small text-white"
                                                   href="{{ sub_category.get_absolute_url }}">
                                                    {{ sub_category }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            {% endfor %}
                    </ul>
                    </li>
                    </ul>
                </div>


                <a class="nav-link text-info active" href="http://127.0.0.1:8000/api/">API</a>
                <a class="nav-link text-white" href="#">درباره ما</a>
            </div>
        </div>
        <div class="d-flex">
            {% if request.user.is_authenticated %}
                {#                <a class="nav-link active text-white" aria-current="page"#}
                {#                   href="{% url 'account:profile' request.user.id %}">پروفایل</a>#}
                <a class="nav-link active text-white" aria-current="page"
                   href="{% url 'accounts:logout' %}">خروج</a>
            {% else %}
                <a class="nav-link active text-white" aria-current="page" href="{% url 'accounts:register' %}">ثبت
                    نام</a>
                <a class="nav-link active text-white" aria-current="page"
                   href="{% url 'accounts:login' %}">ورود</a>
            {% endif %}
        </div>
    </div>
</nav>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>